"""Deterministic scripted policies for smoke tests and visual demonstrations."""

from __future__ import annotations

from enum import IntEnum
import math

import torch

from rm_referee import constants
from rm_referee.schema import (
    PurchaseKind,
    Role,
    SentryStance,
    Team,
    Weapon,
    slot,
    unit_roles,
    unit_teams,
)
from rm_referee.state import GameState
from rm_world.actions import WorldActions
from rm_world.arena import ArenaGeometry
from rm_world.geometry import NO_TARGET, RUNE_TARGET
from rm_world.geometry import resolve_target_slots
from rm_world.kinematics import KinematicState


MOBILE_UNIT_SLOTS = (0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13)
TACTICAL_PHASE_EDGES_S = (60.0, 180.0, 330.0)


class TacticalPhase(IntEnum):
    """Human-readable strategic phases used by the scripted demonstrator."""

    OPENING = 0
    TERRAIN_CONTROL = 1
    OUTPOST_PRESSURE = 2
    FINAL_ASSAULT = 3


TACTICAL_PHASE_LABELS = (
    "OPENING DEPLOYMENT",
    "TERRAIN CONTROL",
    "OUTPOST PRESSURE",
    "FINAL ASSAULT",
)

# The tactical demonstrator deliberately uses only banked, free support time.
# These are policy choices, not rule constants. The rule engine remains the
# authority for the initial 30s bank and each 20s minute grant.
AERIAL_SORTIE_WINDOWS_S = (
    (5.0, 25.0),
    (65.0, 85.0),
    (125.0, 145.0),
    (185.0, 205.0),
    (245.0, 265.0),
    (305.0, 325.0),
    (365.0, 390.0),
)
AERIAL_RETURN_LEAD_S = (8.0, 10.0, 10.0, 12.0, 12.0, 12.0, 14.0)


class TacticalMission(IntEnum):
    """Stable route identifiers for the stateful tactical baseline."""

    HERO_DEPLOY = 0
    ENGINEER_STAGE = 1
    ENGINEER_RESUPPLY = 2
    ENGINEER_REBUILD = 3
    INFANTRY_3_OPENING = 4
    INFANTRY_3_CONTEST = 5
    INFANTRY_3_OUTPOST = 6
    INFANTRY_3_HOLD = 7
    INFANTRY_3_BASE = 8
    INFANTRY_4_OPENING = 9
    INFANTRY_4_CONTEST = 10
    INFANTRY_4_OUTPOST = 11
    INFANTRY_4_HOLD = 12
    INFANTRY_4_BASE = 13
    AERIAL_OPENING = 14
    AERIAL_CONTROL = 15
    AERIAL_PRESSURE = 16
    AERIAL_ASSAULT = 17
    SENTRY_DEFEND = 18
    SENTRY_FORWARD = 19
    SENTRY_BASE = 20
    AERIAL_RETURN = 21
    AERIAL_PAD = 22
    INFANTRY_3_RECOVER = 23
    INFANTRY_4_RECOVER = 24
    SENTRY_RECOVER = 25


# Red routes are diagram-derived Phase 1 [SIM] navigation corridors. Blue
# routes are generated by the field's official 180-degree center symmetry.
TACTICAL_RED_ROUTES: dict[TacticalMission, tuple[tuple[float, float], ...]] = {
    TacticalMission.HERO_DEPLOY: ((-9.4, -1.45),),
    TacticalMission.ENGINEER_STAGE: (
        (-11.6, -4.8),
        (-7.0, -4.8),
        (-4.7, -3.1),
        (-2.7, -3.0),
        (-1.2, -1.8),
    ),
    TacticalMission.ENGINEER_RESUPPLY: (
        (-2.7, -3.0),
        (-4.7, -3.1),
        (-7.0, -4.8),
        (-11.5, -5.2),
    ),
    TacticalMission.ENGINEER_REBUILD: (
        (-1.8, -2.5),
        (-2.2, -2.8),
    ),
    TacticalMission.INFANTRY_3_OPENING: (
        (-10.2, -5.4),
        (-7.0, -5.4),
        (-4.8, -4.2),
        (-2.8, -3.25),
    ),
    TacticalMission.INFANTRY_3_CONTEST: (
        (-1.2, -3.2),
        (1.2, -3.2),
        (2.7, -3.1),
    ),
    TacticalMission.INFANTRY_3_OUTPOST: (
        (4.7, -3.0),
        (5.1, -1.8),
        (4.8, 1.7),
        (3.9, 2.65),
    ),
    TacticalMission.INFANTRY_3_HOLD: ((3.9, 2.65),),
    TacticalMission.INFANTRY_3_BASE: (
        (6.9, -2.5),
        (9.0, -2.7),
        (10.8, -1.6),
        (11.2, -1.0),
    ),
    TacticalMission.INFANTRY_3_RECOVER: (
        (4.8, 1.8),
        (4.8, -2.8),
        (2.7, -3.2),
        (0.0, -3.2),
        (-2.2, -2.8),
    ),
    TacticalMission.INFANTRY_4_OPENING: (
        (-9.5, 6.45),
        (-7.2, 6.45),
        (-6.7, 5.6),
        (-6.2, 4.2),
        (-5.4, 3.0),
        (-2.8, 3.05),
    ),
    TacticalMission.INFANTRY_4_CONTEST: (
        (-1.0, 3.0),
        (1.0, 3.0),
        (1.8, 2.4),
    ),
    TacticalMission.INFANTRY_4_OUTPOST: ((2.0, 2.65),),
    TacticalMission.INFANTRY_4_HOLD: ((2.0, 2.65),),
    TacticalMission.INFANTRY_4_BASE: (
        (6.9, 2.5),
        (9.0, 2.7),
        (10.8, 1.6),
        (11.2, 1.0),
    ),
    TacticalMission.INFANTRY_4_RECOVER: (
        (0.0, 3.0),
        (-2.8, 3.0),
        (-5.2, 3.0),
        (-5.2, -2.8),
        (-3.8, -3.0),
        (-2.2, -2.8),
    ),
    TacticalMission.AERIAL_OPENING: (
        (-9.0, 5.5),
        (-4.5, 4.8),
        (-1.5, 4.2),
    ),
    TacticalMission.AERIAL_CONTROL: ((1.5, 4.2),),
    TacticalMission.AERIAL_PRESSURE: ((4.8, 2.8),),
    TacticalMission.AERIAL_ASSAULT: ((9.5, 2.4),),
    TacticalMission.AERIAL_RETURN: (
        (-9.0, 5.5),
        (-12.4, 5.1),
        (-13.0, 5.0),
    ),
    TacticalMission.AERIAL_PAD: ((-13.0, 5.0),),
    TacticalMission.SENTRY_DEFEND: (
        (-6.0, -3.0),
        (-4.8, -3.0),
        (-3.5, -3.2),
        (-2.0, -4.3),
    ),
    TacticalMission.SENTRY_FORWARD: (
        (-5.5, 2.8),
        (-2.8, 2.8),
        (0.0, 2.7),
        (2.7, 2.8),
    ),
    TacticalMission.SENTRY_BASE: (
        (4.8, 2.8),
        (6.9, 2.5),
        (9.2, 2.5),
        (10.7, 1.8),
    ),
    TacticalMission.SENTRY_RECOVER: (
        (0.0, 3.0),
        (-2.8, 3.0),
        (-5.2, 3.0),
        (-5.2, -2.8),
        (-3.8, -3.0),
        (-2.2, -2.8),
    ),
}


def tactical_phase(elapsed_s: torch.Tensor) -> torch.Tensor:
    """Return the four-phase scripted strategy index for each environment."""

    phase = torch.zeros_like(elapsed_s, dtype=torch.long)
    for edge in TACTICAL_PHASE_EDGES_S:
        phase += elapsed_s >= edge
    return phase


def tactical_phase_label(elapsed_s: float) -> str:
    """Return a display label for a scalar match timestamp."""

    phase = sum(elapsed_s >= edge for edge in TACTICAL_PHASE_EDGES_S)
    return TACTICAL_PHASE_LABELS[phase]


def aerial_sortie_state(elapsed_s: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    """Return scripted support-request and return-to-pad masks.

    The masks schedule free tactical sorties while the referee independently
    enforces the official bank, paid overtime, pad, and radar-lock rules.
    """

    requested = torch.zeros_like(elapsed_s, dtype=torch.bool)
    returning = torch.zeros_like(elapsed_s, dtype=torch.bool)
    for (start_s, end_s), return_lead_s in zip(
        AERIAL_SORTIE_WINDOWS_S,
        AERIAL_RETURN_LEAD_S,
        strict=True,
    ):
        in_window = (elapsed_s >= start_s) & (elapsed_s < end_s)
        requested |= in_window
        returning |= in_window & (elapsed_s >= end_s - return_lead_s)
    return requested, returning


def tactical_route_waypoints(
    mission: TacticalMission | int,
    team: Team | int,
    *,
    device: torch.device | str,
    dtype: torch.dtype,
) -> torch.Tensor:
    """Return one mission route, rotated for the requested team."""

    route = torch.tensor(
        TACTICAL_RED_ROUTES[TacticalMission(mission)],
        device=device,
        dtype=dtype,
    )
    return route if int(team) == Team.RED else -route


class ScriptedOpponent:
    """A small objective-first policy, intentionally free of hidden state."""

    def __init__(self, *, cruise_speed_mps: float = 2.0, fire_range_m: float = 12.0) -> None:
        self.cruise_speed_mps = cruise_speed_mps
        self.fire_range_m = fire_range_m

    def act(
        self,
        game: GameState,
        world: KinematicState,
        *,
        team: Team | int | None = None,
    ) -> WorldActions:
        actions = WorldActions.zeros(game)
        roles = unit_roles(game.device)
        unit_team = torch.arange(constants.UNIT_COUNT, device=game.device) // (
            constants.ROLES_PER_TEAM
        )
        controlled = torch.ones(
            constants.UNIT_COUNT,
            device=game.device,
            dtype=torch.bool,
        )
        if team is not None:
            controlled = unit_team == int(team)

        enemy_outpost_alive = game.alive[:, (15, 7)][:, unit_team]
        target_choice = torch.where(
            enemy_outpost_alive,
            torch.full(
                (game.num_envs, constants.UNIT_COUNT),
                6,
                device=game.device,
                dtype=torch.long,
            ),
            torch.full(
                (game.num_envs, constants.UNIT_COUNT),
                5,
                device=game.device,
                dtype=torch.long,
            ),
        )
        enemy_objective_slot = torch.where(
            enemy_outpost_alive,
            (1 - unit_team)[None, :] * constants.ROLES_PER_TEAM + Role.OUTPOST,
            (1 - unit_team)[None, :] * constants.ROLES_PER_TEAM + Role.BASE,
        )
        objective_xy = torch.gather(
            world.position_xy,
            1,
            enemy_objective_slot[:, :, None].expand(-1, -1, 2),
        )
        delta = objective_xy - world.position_xy
        distance = torch.linalg.vector_norm(delta, dim=-1)
        desired_world = (
            delta / torch.clamp(distance[:, :, None], min=1.0e-6) * self.cruise_speed_mps
        )
        cosine = torch.cos(world.yaw)
        sine = torch.sin(world.yaw)
        body_velocity = torch.stack(
            (
                cosine * desired_world[..., 0] + sine * desired_world[..., 1],
                -sine * desired_world[..., 0] + cosine * desired_world[..., 1],
            ),
            dim=-1,
        )
        movable_role = (roles != Role.BASE) & (roles != Role.OUTPOST)
        actions.body_velocity_xy.copy_(
            torch.where(
                (controlled & movable_role)[None, :, None],
                body_velocity,
                actions.body_velocity_xy,
            )
        )
        desired_yaw = torch.atan2(delta[..., 1], delta[..., 0])
        yaw_error = torch.atan2(
            torch.sin(desired_yaw - world.yaw),
            torch.cos(desired_yaw - world.yaw),
        )
        actions.yaw_rate.copy_(
            torch.where(
                (controlled & movable_role)[None, :],
                torch.clamp(yaw_error * 3.0, min=-math.pi, max=math.pi),
                actions.yaw_rate,
            )
        )

        launcher_role = (
            (roles == Role.HERO)
            | (roles == Role.INFANTRY_3)
            | (roles == Role.INFANTRY_4)
            | (roles == Role.AERIAL)
            | (roles == Role.SENTRY)
        )
        rune_active = game.rune_mode[:, unit_team] != 0
        target_choice = torch.where(
            rune_active & launcher_role[None, :],
            torch.full_like(target_choice, RUNE_TARGET),
            target_choice,
        )
        actions.target.copy_(
            torch.where(
                controlled[None, :],
                target_choice,
                torch.full_like(target_choice, NO_TARGET),
            )
        )
        actions.fire.copy_(
            controlled[None, :]
            & launcher_role[None, :]
            & game.alive
            & ((distance <= self.fire_range_m) | rune_active)
        )

        controlled_teams = torch.ones(
            constants.TEAM_COUNT,
            device=game.device,
            dtype=torch.bool,
        )
        if team is not None:
            controlled_teams = torch.arange(constants.TEAM_COUNT, device=game.device) == int(team)
        actions.aerial_support.copy_(controlled_teams[None, :] & (game.aerial_support_bank_s > 0))
        radar_target = torch.tensor(
            [constants.ROLES_PER_TEAM + Role.INFANTRY_3, Role.INFANTRY_3],
            device=game.device,
            dtype=torch.long,
        )
        actions.radar_target.copy_(
            torch.where(
                controlled_teams[None, :],
                radar_target[None, :],
                torch.full_like(actions.radar_target, -1),
            )
        )
        actions.radar_report_xy.copy_(
            torch.gather(
                world.position_xy,
                1,
                radar_target[None, :, None].expand(game.num_envs, -1, 2),
            )
        )
        return actions


class TacticalScriptedOpponent:
    """Stateful, role-specific baseline for readable match demonstrations.

    This is deliberately a scripted baseline rather than a trained policy. It
    advances routes by spatial progress, reacts to objective state, brakes at
    holding points, and applies local separation before the physical contact
    solver. The simpler :class:`ScriptedOpponent` remains the batched training
    and evaluation smoke-test opponent.
    """

    def __init__(
        self,
        *,
        arena: ArenaGeometry | None = None,
        waypoint_tolerance_m: float = 0.38,
    ) -> None:
        if waypoint_tolerance_m <= 0:
            raise ValueError("waypoint_tolerance_m must be positive")
        self.arena = arena or ArenaGeometry()
        self.waypoint_tolerance_m = waypoint_tolerance_m
        self._objective_policy = ScriptedOpponent()
        self._route_id: torch.Tensor | None = None
        self._waypoint_index: torch.Tensor | None = None
        self._last_elapsed_s: torch.Tensor | None = None
        self._current_missions: torch.Tensor | None = None

    @property
    def current_missions(self) -> torch.Tensor | None:
        """Return the last computed mission tensor, if ``act`` has run."""

        return self._current_missions

    def reset(self) -> None:
        """Forget route progress; the next action starts every active route."""

        self._route_id = None
        self._waypoint_index = None
        self._last_elapsed_s = None
        self._current_missions = None

    def _controlled_units(
        self,
        game: GameState,
        team: Team | int | None,
    ) -> torch.Tensor:
        controlled = torch.ones(
            constants.UNIT_COUNT,
            device=game.device,
            dtype=torch.bool,
        )
        if team is not None:
            controlled = unit_teams(game.device) == int(team)
        return controlled

    def _controlled_teams(
        self,
        game: GameState,
        team: Team | int | None,
    ) -> torch.Tensor:
        controlled = torch.ones(
            constants.TEAM_COUNT,
            device=game.device,
            dtype=torch.bool,
        )
        if team is not None:
            controlled = torch.arange(constants.TEAM_COUNT, device=game.device) == int(team)
        return controlled

    def _missions(self, game: GameState) -> torch.Tensor:
        phase = tactical_phase(game.elapsed_s)
        missions = torch.full(
            (game.num_envs, constants.UNIT_COUNT),
            int(TacticalMission.HERO_DEPLOY),
            device=game.device,
            dtype=torch.long,
        )
        for team in (Team.RED, Team.BLUE):
            offset = int(team) * constants.ROLES_PER_TEAM
            own_outpost = slot(team, Role.OUTPOST)
            enemy_outpost = slot(1 - int(team), Role.OUTPOST)

            missions[:, offset + Role.HERO] = int(TacticalMission.HERO_DEPLOY)

            engineer = offset + Role.ENGINEER
            engineer_low = game.hp[:, engineer] < game.max_hp[:, engineer] * 0.45
            can_rebuild = (
                ~game.alive[:, own_outpost]
                & (game.outpost_rebuild_charges[:, team] > 0)
                & (game.elapsed_s < constants.OUTPOST_REBUILD_DEADLINE_S)
            )
            engineer_mission = torch.full_like(
                phase,
                int(TacticalMission.ENGINEER_STAGE),
            )
            engineer_mission = torch.where(
                engineer_low,
                int(TacticalMission.ENGINEER_RESUPPLY),
                engineer_mission,
            )
            engineer_mission = torch.where(
                can_rebuild,
                int(TacticalMission.ENGINEER_REBUILD),
                engineer_mission,
            )
            missions[:, engineer] = engineer_mission

            enemy_outpost_alive = game.alive[:, enemy_outpost]
            infantry_3_mission = torch.where(
                phase == TacticalPhase.OPENING,
                int(TacticalMission.INFANTRY_3_OPENING),
                int(TacticalMission.INFANTRY_3_CONTEST),
            )
            infantry_3_mission = torch.where(
                phase >= TacticalPhase.OUTPOST_PRESSURE,
                torch.where(
                    enemy_outpost_alive,
                    int(TacticalMission.INFANTRY_3_OUTPOST),
                    int(TacticalMission.INFANTRY_3_HOLD),
                ),
                infantry_3_mission,
            )
            infantry_3_mission = torch.where(
                (phase == TacticalPhase.FINAL_ASSAULT) & ~enemy_outpost_alive,
                int(TacticalMission.INFANTRY_3_BASE),
                infantry_3_mission,
            )
            infantry_3_mission = torch.where(
                game.weak[:, offset + Role.INFANTRY_3],
                int(TacticalMission.INFANTRY_3_RECOVER),
                infantry_3_mission,
            )
            missions[:, offset + Role.INFANTRY_3] = infantry_3_mission

            infantry_4_mission = torch.where(
                phase == TacticalPhase.OPENING,
                int(TacticalMission.INFANTRY_4_OPENING),
                int(TacticalMission.INFANTRY_4_CONTEST),
            )
            infantry_4_mission = torch.where(
                phase >= TacticalPhase.OUTPOST_PRESSURE,
                torch.where(
                    enemy_outpost_alive,
                    int(TacticalMission.INFANTRY_4_OUTPOST),
                    int(TacticalMission.INFANTRY_4_HOLD),
                ),
                infantry_4_mission,
            )
            infantry_4_mission = torch.where(
                (phase == TacticalPhase.FINAL_ASSAULT) & ~enemy_outpost_alive,
                int(TacticalMission.INFANTRY_4_BASE),
                infantry_4_mission,
            )
            infantry_4_mission = torch.where(
                game.weak[:, offset + Role.INFANTRY_4],
                int(TacticalMission.INFANTRY_4_RECOVER),
                infantry_4_mission,
            )
            missions[:, offset + Role.INFANTRY_4] = infantry_4_mission

            aerial_by_phase = torch.tensor(
                (
                    int(TacticalMission.AERIAL_OPENING),
                    int(TacticalMission.AERIAL_CONTROL),
                    int(TacticalMission.AERIAL_PRESSURE),
                    int(TacticalMission.AERIAL_ASSAULT),
                ),
                device=game.device,
                dtype=torch.long,
            )
            sortie_requested, sortie_returning = aerial_sortie_state(
                game.elapsed_s,
            )
            aerial_mission = torch.where(
                sortie_requested,
                aerial_by_phase[phase],
                int(TacticalMission.AERIAL_PAD),
            )
            aerial_mission = torch.where(
                sortie_returning,
                int(TacticalMission.AERIAL_RETURN),
                aerial_mission,
            )
            missions[:, offset + Role.AERIAL] = aerial_mission

            own_outpost_fraction = game.hp[:, own_outpost] / torch.clamp(
                game.max_hp[:, own_outpost],
                min=1.0,
            )
            defend = game.alive[:, own_outpost] & (
                (phase < TacticalPhase.OUTPOST_PRESSURE) | (own_outpost_fraction < 0.65)
            )
            sentry_mission = torch.where(
                defend,
                int(TacticalMission.SENTRY_DEFEND),
                int(TacticalMission.SENTRY_FORWARD),
            )
            sentry_mission = torch.where(
                (phase == TacticalPhase.FINAL_ASSAULT) & ~enemy_outpost_alive,
                int(TacticalMission.SENTRY_BASE),
                sentry_mission,
            )
            sentry_mission = torch.where(
                game.weak[:, offset + Role.SENTRY],
                int(TacticalMission.SENTRY_RECOVER),
                sentry_mission,
            )
            missions[:, offset + Role.SENTRY] = sentry_mission
        return missions

    def _ensure_route_state(self, game: GameState) -> None:
        expected_shape = (game.num_envs, constants.UNIT_COUNT)
        if (
            self._route_id is None
            or self._route_id.shape != expected_shape
            or self._route_id.device != game.device
        ):
            self._route_id = torch.full(
                expected_shape,
                -1,
                device=game.device,
                dtype=torch.long,
            )
            self._waypoint_index = torch.zeros(
                expected_shape,
                device=game.device,
                dtype=torch.long,
            )
            self._last_elapsed_s = torch.full_like(game.elapsed_s, -1.0)

    def _route_targets(
        self,
        game: GameState,
        world: KinematicState,
        missions: torch.Tensor,
    ) -> torch.Tensor:
        self._ensure_route_state(game)
        assert self._route_id is not None
        assert self._waypoint_index is not None
        assert self._last_elapsed_s is not None

        reset_env = game.elapsed_s + 1.0e-6 < self._last_elapsed_s
        self._route_id[reset_env] = -1
        self._waypoint_index[reset_env] = 0

        changed = missions != self._route_id
        self._waypoint_index.masked_fill_(changed, 0)
        self._route_id.copy_(missions)

        targets = world.position_xy.clone()
        teams = unit_teams(game.device)
        symmetry = torch.where(
            teams == Team.RED,
            torch.ones(constants.UNIT_COUNT, device=game.device, dtype=game.dtype),
            -torch.ones(constants.UNIT_COUNT, device=game.device, dtype=game.dtype),
        )
        for mission, route_points in TACTICAL_RED_ROUTES.items():
            route = torch.tensor(
                route_points,
                device=game.device,
                dtype=game.dtype,
            )
            active = missions == int(mission)
            symmetric_route = route[None, None, :, :] * symmetry[None, :, None, None]
            nearest_route_index = torch.linalg.vector_norm(
                symmetric_route - world.position_xy[:, :, None, :],
                dim=-1,
            ).argmin(dim=-1)
            self._waypoint_index.copy_(
                torch.where(
                    active & changed,
                    nearest_route_index,
                    self._waypoint_index,
                )
            )
            route_index = torch.clamp(
                self._waypoint_index,
                max=route.shape[0] - 1,
            )
            candidate = route[route_index] * symmetry[None, :, None]
            distance = torch.linalg.vector_norm(
                candidate - world.position_xy,
                dim=-1,
            )
            advance = (
                active
                & (distance <= self.waypoint_tolerance_m)
                & (route_index < route.shape[0] - 1)
            )
            self._waypoint_index.add_(advance.to(torch.long))
            route_index = torch.clamp(
                self._waypoint_index,
                max=route.shape[0] - 1,
            )
            candidate = route[route_index] * symmetry[None, :, None]
            targets.copy_(torch.where(active[:, :, None], candidate, targets))

        self._last_elapsed_s.copy_(game.elapsed_s)
        self._current_missions = missions.clone()
        return targets

    def _apply_combat(
        self,
        actions: WorldActions,
        game: GameState,
        world: KinematicState,
        controlled: torch.Tensor,
    ) -> None:
        roles = unit_roles(game.device)
        teams = unit_teams(game.device)
        enemy_teams = 1 - teams
        candidate_roles = torch.tensor(
            (Role.HERO, Role.ENGINEER, Role.INFANTRY_3, Role.INFANTRY_4, Role.SENTRY),
            device=game.device,
            dtype=torch.long,
        )
        candidate_slots = enemy_teams[:, None] * constants.ROLES_PER_TEAM + candidate_roles[None, :]
        candidate_xy = world.position_xy[:, candidate_slots]
        candidate_distance = torch.linalg.vector_norm(
            candidate_xy - world.position_xy[:, :, None, :],
            dim=-1,
        )
        candidate_alive = game.alive[:, candidate_slots]
        candidate_distance = torch.where(
            candidate_alive,
            candidate_distance,
            torch.full_like(candidate_distance, torch.inf),
        )
        nearest_distance, nearest_index = candidate_distance.min(dim=-1)
        nearest_choice = nearest_index

        engage_range = torch.tensor(
            (0.0, 0.0, 7.5, 7.0, 8.5, 8.0, 0.0, 0.0) * constants.TEAM_COUNT,
            device=game.device,
            dtype=game.dtype,
        )
        use_nearby = nearest_distance <= engage_range[None, :]
        enemy_outpost_slots = enemy_teams * constants.ROLES_PER_TEAM + int(Role.OUTPOST)
        enemy_outpost_alive = game.alive[:, enemy_outpost_slots]
        phase = tactical_phase(game.elapsed_s)
        pressure = phase >= TacticalPhase.OUTPOST_PRESSURE
        final_assault = phase == TacticalPhase.FINAL_ASSAULT
        fallback = torch.where(
            pressure[:, None] & enemy_outpost_alive,
            torch.full_like(nearest_choice, 6),
            torch.where(
                final_assault[:, None],
                torch.full_like(nearest_choice, 5),
                torch.full_like(nearest_choice, NO_TARGET),
            ),
        )
        skirmisher = (
            (roles == Role.INFANTRY_3)
            | (roles == Role.INFANTRY_4)
            | (roles == Role.AERIAL)
            | (roles == Role.SENTRY)
        )
        target_choice = torch.where(
            use_nearby & skirmisher[None, :],
            nearest_choice,
            fallback,
        )
        objective_attacker = (
            (roles == Role.HERO) | (roles == Role.INFANTRY_3) | (roles == Role.INFANTRY_4)
        )
        force_objective = objective_attacker[None, :] & (
            (pressure[:, None] & enemy_outpost_alive)
            | (final_assault[:, None] & ~enemy_outpost_alive)
        )
        target_choice = torch.where(
            force_objective,
            fallback,
            target_choice,
        )
        target_choice = torch.where(
            roles[None, :] == Role.ENGINEER,
            torch.full_like(target_choice, NO_TARGET),
            target_choice,
        )
        actions.target.copy_(
            torch.where(
                controlled[None, :],
                target_choice,
                actions.target,
            )
        )

        target_slots = resolve_target_slots(actions.target)
        target_safe = torch.clamp(target_slots, min=0)
        target_xy = torch.gather(
            world.position_xy,
            1,
            target_safe[:, :, None].expand(-1, -1, 2),
        )
        target_distance = torch.linalg.vector_norm(
            target_xy - world.position_xy,
            dim=-1,
        )
        line_of_sight = self.arena.line_of_sight(world.position_xy, target_xy)
        launcher = (
            (roles == Role.HERO)
            | (roles == Role.INFANTRY_3)
            | (roles == Role.INFANTRY_4)
            | (roles == Role.AERIAL)
            | (roles == Role.SENTRY)
        )
        fire_range = torch.tensor(
            (16.0, 0.0, 9.0, 9.0, 10.0, 11.0, 0.0, 0.0) * constants.TEAM_COUNT,
            device=game.device,
            dtype=game.dtype,
        )
        weapon = torch.where(
            roles == Role.HERO,
            torch.full_like(roles, Weapon.MM42),
            torch.full_like(roles, Weapon.MM17),
        )
        ammo = torch.gather(
            game.ammo,
            2,
            weapon[None, :, None].expand(game.num_envs, -1, 1),
        ).squeeze(-1)
        base_fire_period = torch.tensor(
            (5, 99, 4, 5, 4, 3, 99, 99) * constants.TEAM_COUNT,
            device=game.device,
            dtype=torch.long,
        )
        terrain_control = phase == TacticalPhase.TERRAIN_CONTROL
        fire_period = base_fire_period[None, :] * torch.where(
            terrain_control[:, None],
            torch.full(
                (game.num_envs, constants.UNIT_COUNT),
                3,
                device=game.device,
                dtype=torch.long,
            ),
            torch.ones(
                (game.num_envs, constants.UNIT_COUNT),
                device=game.device,
                dtype=torch.long,
            ),
        )
        policy_tick = torch.floor(game.elapsed_s * 5.0 + 1.0e-4).to(torch.long)
        unit_index = torch.arange(constants.UNIT_COUNT, device=game.device)
        cadence = ((policy_tick[:, None] + unit_index[None, :]) % fire_period) == 0
        _, aerial_returning = aerial_sortie_state(game.elapsed_s)
        actions.fire.copy_(
            controlled[None, :]
            & launcher[None, :]
            & game.alive
            & ~game.weak
            & (phase != TacticalPhase.OPENING)[:, None]
            & ~(aerial_returning[:, None] & (roles == Role.AERIAL)[None, :])
            & (target_slots >= 0)
            & (target_distance <= fire_range[None, :])
            & line_of_sight
            & (ammo > 0)
            & cadence
        )

    def _apply_economy(
        self,
        actions: WorldActions,
        game: GameState,
        controlled_teams: torch.Tensor,
    ) -> None:
        """Buy 17mm rounds for infantry through the official remote flow."""

        for team in (Team.RED, Team.BLUE):
            infantry = torch.tensor(
                (
                    slot(team, Role.INFANTRY_3),
                    slot(team, Role.INFANTRY_4),
                ),
                device=game.device,
                dtype=torch.long,
            )
            ammo = game.ammo[:, infantry, Weapon.MM17]
            eligible = game.out_of_combat_s[:, infantry] >= constants.OUT_OF_COMBAT_S
            selection_score = torch.where(
                eligible,
                ammo,
                torch.full_like(ammo, torch.iinfo(ammo.dtype).max),
            )
            selected_index = selection_score.argmin(dim=1)
            selected_unit = infantry[selected_index]
            can_request = (
                controlled_teams[team]
                & eligible.any(dim=1)
                & (game.pending_purchase_kind[:, team] == PurchaseKind.NONE)
                & (game.team_coin[:, team] >= constants.REMOTE_PURCHASE_COST)
                & (
                    game.team_purchased_ammo[:, team, Weapon.MM17]
                    + constants.REMOTE_PURCHASE_ROUNDS[Weapon.MM17]
                    <= constants.PURCHASE_CAP_PER_TEAM[Weapon.MM17]
                )
            )
            actions.purchase_unit[:, team] = torch.where(
                can_request,
                selected_unit,
                actions.purchase_unit[:, team],
            )
            actions.purchase_weapon[:, team] = torch.where(
                can_request,
                torch.full_like(
                    actions.purchase_weapon[:, team],
                    int(Weapon.MM17),
                ),
                actions.purchase_weapon[:, team],
            )
            actions.purchase_kind[:, team] = torch.where(
                can_request,
                torch.full_like(
                    actions.purchase_kind[:, team],
                    int(PurchaseKind.REMOTE),
                ),
                actions.purchase_kind[:, team],
            )

    def _apply_motion(
        self,
        actions: WorldActions,
        game: GameState,
        world: KinematicState,
        missions: torch.Tensor,
        controlled: torch.Tensor,
        controlled_teams: torch.Tensor,
    ) -> None:
        targets = self._route_targets(game, world, missions)
        roles = unit_roles(game.device)
        delta = targets - world.position_xy
        distance = torch.linalg.vector_norm(delta, dim=-1)
        direction = delta / torch.clamp(distance[:, :, None], min=1.0e-6)
        cruise_speed = torch.tensor(
            (1.25, 1.55, 2.05, 2.0, 2.35, 1.75, 0.0, 0.0) * constants.TEAM_COUNT,
            device=game.device,
            dtype=game.dtype,
        )
        commanded_speed = torch.minimum(
            cruise_speed[None, :],
            distance * 1.6,
        )
        commanded_speed = torch.where(
            distance < 0.10,
            torch.zeros_like(commanded_speed),
            commanded_speed,
        )
        desired_world = direction * commanded_speed[:, :, None]

        pair_delta = world.position_xy[:, :, None, :] - world.position_xy[:, None, :, :]
        pair_distance = torch.linalg.vector_norm(pair_delta, dim=-1)
        pair_direction = pair_delta / torch.clamp(
            pair_distance[:, :, :, None],
            min=1.0e-6,
        )
        radius = torch.where(
            roles == Role.BASE,
            torch.full(
                (constants.UNIT_COUNT,),
                0.95,
                device=game.device,
                dtype=game.dtype,
            ),
            torch.full(
                (constants.UNIT_COUNT,),
                0.40,
                device=game.device,
                dtype=game.dtype,
            ),
        )
        preferred_distance = radius[:, None] + radius[None, :] + 0.30
        separation = torch.clamp(
            (preferred_distance[None, :, :] - pair_distance) / 0.55,
            min=0.0,
            max=1.0,
        )
        identity = torch.eye(
            constants.UNIT_COUNT,
            device=game.device,
            dtype=torch.bool,
        )
        ground_mobile = (roles != Role.AERIAL) & (roles < Role.BASE)
        ground_target = roles != Role.AERIAL
        pair_valid = ground_mobile[:, None] & ground_target[None, :] & ~identity
        repulsion = (pair_direction * separation[:, :, :, None] * pair_valid[None, :, :, None]).sum(
            dim=2
        ) * 0.85
        desired_world += repulsion
        desired_speed = torch.linalg.vector_norm(
            desired_world,
            dim=-1,
            keepdim=True,
        )
        desired_world *= torch.clamp(
            cruise_speed[None, :, None] / torch.clamp(desired_speed, min=1.0e-6),
            max=1.0,
        )

        yaw = world.yaw
        cosine = torch.cos(yaw)
        sine = torch.sin(yaw)
        body_velocity = torch.stack(
            (
                cosine * desired_world[..., 0] + sine * desired_world[..., 1],
                -sine * desired_world[..., 0] + cosine * desired_world[..., 1],
            ),
            dim=-1,
        )
        movable = (roles != Role.BASE) & (roles != Role.OUTPOST)
        command_mask = controlled & movable
        actions.body_velocity_xy.copy_(
            torch.where(
                command_mask[None, :, None],
                body_velocity,
                actions.body_velocity_xy,
            )
        )

        move_yaw = torch.atan2(desired_world[..., 1], desired_world[..., 0])
        target_slots = resolve_target_slots(actions.target)
        target_safe = torch.clamp(target_slots, min=0)
        aim_xy = torch.gather(
            world.position_xy,
            1,
            target_safe[:, :, None].expand(-1, -1, 2),
        )
        aim_delta = aim_xy - world.position_xy
        aim_yaw = torch.atan2(aim_delta[..., 1], aim_delta[..., 0])
        aim = (target_slots >= 0) & ((distance < 0.45) | actions.fire)
        desired_yaw = torch.where(aim, aim_yaw, move_yaw)
        yaw_error = torch.atan2(
            torch.sin(desired_yaw - yaw),
            torch.cos(desired_yaw - yaw),
        )
        actions.yaw_rate.copy_(
            torch.where(
                command_mask[None, :],
                torch.clamp(yaw_error * 3.0, min=-math.pi, max=math.pi),
                actions.yaw_rate,
            )
        )

        aerial = roles == Role.AERIAL
        pad_red = torch.tensor(
            (-13.0, 5.0),
            device=game.device,
            dtype=game.dtype,
        )
        symmetry = torch.where(
            unit_teams(game.device) == Team.RED,
            torch.ones(constants.UNIT_COUNT, device=game.device, dtype=game.dtype),
            -torch.ones(constants.UNIT_COUNT, device=game.device, dtype=game.dtype),
        )
        pad_xy = pad_red[None, :] * symmetry[:, None]
        pad_distance = torch.linalg.vector_norm(
            world.position_xy - pad_xy[None, :, :],
            dim=-1,
        )
        landing_mission = (missions == int(TacticalMission.AERIAL_RETURN)) | (
            missions == int(TacticalMission.AERIAL_PAD)
        )
        landing = landing_mission & (pad_distance < 0.35)
        target_altitude = torch.where(
            landing,
            torch.zeros_like(world.position_z),
            torch.full_like(world.position_z, 1.8),
        )
        altitude_error = target_altitude - world.position_z
        actions.vertical_velocity.copy_(
            torch.where(
                (controlled & aerial)[None, :],
                torch.clamp(altitude_error * 1.5, min=-1.5, max=1.5),
                actions.vertical_velocity,
            )
        )
        sortie_requested, _ = aerial_sortie_state(game.elapsed_s)
        actions.aerial_support.copy_(
            controlled_teams[None, :] & sortie_requested[:, None] & (game.aerial_support_bank_s > 0)
        )

        for team in (Team.RED, Team.BLUE):
            hero = slot(team, Role.HERO)
            engineer = slot(team, Role.ENGINEER)
            hero_at_deploy = distance[:, hero] < 0.28
            team_controlled = controlled_teams[team]
            actions.hero_deploy[:, team] = team_controlled & hero_at_deploy
            actions.rebuild_outpost[:, engineer] = team_controlled & (
                missions[:, engineer] == int(TacticalMission.ENGINEER_REBUILD)
            )
            sentry = slot(team, Role.SENTRY)
            defending = missions[:, sentry] == int(TacticalMission.SENTRY_DEFEND)
            final = tactical_phase(game.elapsed_s) == TacticalPhase.FINAL_ASSAULT
            actions.sentry_stance[:, team] = torch.where(
                team_controlled,
                torch.where(
                    defending,
                    torch.full_like(
                        actions.sentry_stance[:, team],
                        int(SentryStance.DEFENSIVE),
                    ),
                    torch.where(
                        final,
                        torch.full_like(
                            actions.sentry_stance[:, team],
                            int(SentryStance.OFFENSIVE),
                        ),
                        torch.full_like(
                            actions.sentry_stance[:, team],
                            int(SentryStance.MOBILE),
                        ),
                    ),
                ),
                actions.sentry_stance[:, team],
            )

    def act(
        self,
        game: GameState,
        world: KinematicState,
        *,
        team: Team | int | None = None,
    ) -> WorldActions:
        """Return one stateful tactical command frame."""

        actions = self._objective_policy.act(game, world, team=team)
        controlled = self._controlled_units(game, team)
        controlled_teams = self._controlled_teams(game, team)
        missions = self._missions(game)
        self._apply_economy(actions, game, controlled_teams)
        self._apply_combat(actions, game, world, controlled)
        self._apply_motion(
            actions,
            game,
            world,
            missions,
            controlled,
            controlled_teams,
        )
        return actions
